version: '3'
services:
  api:
    environment:
      RESOLVER_SVC: 'resolver-svc:8082'
      VARIABLES_SVC: 'monolith-svc:8081'
    image: chalk-api
    ports:
      - "8080:8080"
  web:
    image: chalk-web
    ports:
      - "8000:8080"
  resolver-svc:
    environment:
      PORT: '8082'
      VARIABLES_SVC: 'monolith-svc:8081'
    image: chalk-resolver-svc
  monolith-svc:
    environment:
      PORT: '8081'
    image: chalk-monolith-svc
