// Code generated by protoc-gen-go. DO NOT EDIT.
// source: domain.proto

package monolith

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_73e6234e76dbdb84, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Session struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Pages                []string `protobuf:"bytes,2,rep,name=pages,proto3" json:"pages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_73e6234e76dbdb84, []int{1}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *Session) GetPages() []string {
	if m != nil {
		return m.Pages
	}
	return nil
}

type Page struct {
	PageId               string   `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Variables            []string `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_73e6234e76dbdb84, []int{2}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetPageId() string {
	if m != nil {
		return m.PageId
	}
	return ""
}

func (m *Page) GetVariables() []string {
	if m != nil {
		return m.Variables
	}
	return nil
}

type Variable struct {
	VariableId           string   `protobuf:"bytes,1,opt,name=variable_id,json=variableId,proto3" json:"variable_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Formula              string   `protobuf:"bytes,3,opt,name=formula,proto3" json:"formula,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Variable) Reset()         { *m = Variable{} }
func (m *Variable) String() string { return proto.CompactTextString(m) }
func (*Variable) ProtoMessage()    {}
func (*Variable) Descriptor() ([]byte, []int) {
	return fileDescriptor_73e6234e76dbdb84, []int{3}
}

func (m *Variable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Variable.Unmarshal(m, b)
}
func (m *Variable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Variable.Marshal(b, m, deterministic)
}
func (m *Variable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Variable.Merge(m, src)
}
func (m *Variable) XXX_Size() int {
	return xxx_messageInfo_Variable.Size(m)
}
func (m *Variable) XXX_DiscardUnknown() {
	xxx_messageInfo_Variable.DiscardUnknown(m)
}

var xxx_messageInfo_Variable proto.InternalMessageInfo

func (m *Variable) GetVariableId() string {
	if m != nil {
		return m.VariableId
	}
	return ""
}

func (m *Variable) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Variable) GetFormula() string {
	if m != nil {
		return m.Formula
	}
	return ""
}

func init() {
	proto.RegisterType((*Error)(nil), "monolith.Error")
	proto.RegisterType((*Session)(nil), "monolith.Session")
	proto.RegisterType((*Page)(nil), "monolith.Page")
	proto.RegisterType((*Variable)(nil), "monolith.Variable")
}

func init() { proto.RegisterFile("domain.proto", fileDescriptor_73e6234e76dbdb84) }

var fileDescriptor_73e6234e76dbdb84 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xbd, 0x4b, 0xc7, 0x30,
	0x10, 0x86, 0xf9, 0x7d, 0xf4, 0x23, 0xa7, 0xd3, 0x21, 0x98, 0x41, 0xb1, 0x66, 0xea, 0xe4, 0xe2,
	0xac, 0x9b, 0x43, 0x37, 0xa9, 0x20, 0x38, 0xc9, 0x95, 0xc4, 0x1a, 0x68, 0x72, 0x25, 0xa9, 0xfe,
	0xfd, 0xd2, 0x36, 0xb5, 0xdb, 0x3d, 0xcf, 0xe5, 0x0d, 0xbc, 0x07, 0x97, 0x9a, 0x1d, 0x59, 0xff,
	0x30, 0x06, 0x9e, 0x18, 0x4b, 0xc7, 0x9e, 0x07, 0x3b, 0x7d, 0xab, 0x7b, 0xc8, 0x5e, 0x42, 0xe0,
	0x80, 0x12, 0x0a, 0x67, 0x62, 0xa4, 0xde, 0xc8, 0x43, 0x75, 0xa8, 0x45, 0xbb, 0xa1, 0x7a, 0x86,
	0xe2, 0xcd, 0xc4, 0x68, 0xd9, 0xe3, 0x2d, 0x40, 0x5c, 0xc7, 0x4f, 0xab, 0xd3, 0x3b, 0x91, 0x4c,
	0xa3, 0xf1, 0x0a, 0xb2, 0x91, 0x7a, 0x13, 0xe5, 0xb1, 0x3a, 0xd5, 0xa2, 0x5d, 0x41, 0x3d, 0xc1,
	0xf9, 0x95, 0x7a, 0x83, 0xd7, 0x50, 0xcc, 0x62, 0x4f, 0xe6, 0x33, 0x36, 0x1a, 0x6f, 0x40, 0xfc,
	0x52, 0xb0, 0xd4, 0x0d, 0xff, 0xd1, 0x5d, 0xa8, 0x0f, 0x28, 0xdf, 0x13, 0xe0, 0x1d, 0x5c, 0x6c,
	0x8b, 0xfd, 0x1b, 0xd8, 0x54, 0xa3, 0x11, 0xe1, 0xec, 0xc9, 0x19, 0x79, 0x5c, 0x36, 0xcb, 0x3c,
	0x37, 0xfb, 0xe2, 0xe0, 0x7e, 0x06, 0x92, 0xa7, 0xb5, 0x59, 0xc2, 0x2e, 0x5f, 0xae, 0xf1, 0xf8,
	0x17, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xbb, 0x4c, 0x92, 0x1d, 0x01, 0x00, 0x00,
}
