// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pages.proto

package monolith

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreatePageRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePageRequest) Reset()         { *m = CreatePageRequest{} }
func (m *CreatePageRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePageRequest) ProtoMessage()    {}
func (*CreatePageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20be0c8f23cb364f, []int{0}
}

func (m *CreatePageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePageRequest.Unmarshal(m, b)
}
func (m *CreatePageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePageRequest.Marshal(b, m, deterministic)
}
func (m *CreatePageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePageRequest.Merge(m, src)
}
func (m *CreatePageRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePageRequest.Size(m)
}
func (m *CreatePageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePageRequest proto.InternalMessageInfo

type CreatePageResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Page                 *Page    `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePageResponse) Reset()         { *m = CreatePageResponse{} }
func (m *CreatePageResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePageResponse) ProtoMessage()    {}
func (*CreatePageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_20be0c8f23cb364f, []int{1}
}

func (m *CreatePageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePageResponse.Unmarshal(m, b)
}
func (m *CreatePageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePageResponse.Marshal(b, m, deterministic)
}
func (m *CreatePageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePageResponse.Merge(m, src)
}
func (m *CreatePageResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePageResponse.Size(m)
}
func (m *CreatePageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePageResponse proto.InternalMessageInfo

func (m *CreatePageResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *CreatePageResponse) GetPage() *Page {
	if m != nil {
		return m.Page
	}
	return nil
}

type GetPagesRequest struct {
	PageIds              []string `protobuf:"bytes,1,rep,name=page_ids,json=pageIds,proto3" json:"page_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPagesRequest) Reset()         { *m = GetPagesRequest{} }
func (m *GetPagesRequest) String() string { return proto.CompactTextString(m) }
func (*GetPagesRequest) ProtoMessage()    {}
func (*GetPagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20be0c8f23cb364f, []int{2}
}

func (m *GetPagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPagesRequest.Unmarshal(m, b)
}
func (m *GetPagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPagesRequest.Marshal(b, m, deterministic)
}
func (m *GetPagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPagesRequest.Merge(m, src)
}
func (m *GetPagesRequest) XXX_Size() int {
	return xxx_messageInfo_GetPagesRequest.Size(m)
}
func (m *GetPagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPagesRequest proto.InternalMessageInfo

func (m *GetPagesRequest) GetPageIds() []string {
	if m != nil {
		return m.PageIds
	}
	return nil
}

type GetPagesResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Pages                []*Page  `protobuf:"bytes,2,rep,name=pages,proto3" json:"pages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPagesResponse) Reset()         { *m = GetPagesResponse{} }
func (m *GetPagesResponse) String() string { return proto.CompactTextString(m) }
func (*GetPagesResponse) ProtoMessage()    {}
func (*GetPagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_20be0c8f23cb364f, []int{3}
}

func (m *GetPagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPagesResponse.Unmarshal(m, b)
}
func (m *GetPagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPagesResponse.Marshal(b, m, deterministic)
}
func (m *GetPagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPagesResponse.Merge(m, src)
}
func (m *GetPagesResponse) XXX_Size() int {
	return xxx_messageInfo_GetPagesResponse.Size(m)
}
func (m *GetPagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPagesResponse proto.InternalMessageInfo

func (m *GetPagesResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *GetPagesResponse) GetPages() []*Page {
	if m != nil {
		return m.Pages
	}
	return nil
}

func init() {
	proto.RegisterType((*CreatePageRequest)(nil), "monolith.CreatePageRequest")
	proto.RegisterType((*CreatePageResponse)(nil), "monolith.CreatePageResponse")
	proto.RegisterType((*GetPagesRequest)(nil), "monolith.GetPagesRequest")
	proto.RegisterType((*GetPagesResponse)(nil), "monolith.GetPagesResponse")
}

func init() { proto.RegisterFile("pages.proto", fileDescriptor_20be0c8f23cb364f) }

var fileDescriptor_20be0c8f23cb364f = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x71, 0x4b, 0x20, 0x4c, 0x11, 0x85, 0x61, 0xe3, 0x1a, 0x16, 0x91, 0x05, 0x52, 0x17,
	0x28, 0x8b, 0x72, 0x84, 0x0a, 0xa1, 0xee, 0x50, 0x2e, 0x10, 0x19, 0x65, 0x54, 0x22, 0x91, 0x38,
	0xd8, 0xe6, 0x2c, 0x5c, 0x17, 0xd9, 0x26, 0x32, 0x82, 0x6c, 0xba, 0xf4, 0x7f, 0x5f, 0x7f, 0xfe,
	0x8c, 0x61, 0x31, 0xa8, 0x3d, 0xd9, 0x72, 0x30, 0xda, 0x69, 0xcc, 0x3b, 0xdd, 0xeb, 0xf7, 0xd6,
	0xbd, 0x89, 0xf3, 0x46, 0x77, 0xaa, 0xed, 0xa3, 0x2e, 0xaf, 0xe1, 0x6a, 0x6b, 0x48, 0x39, 0x7a,
	0x51, 0x7b, 0xaa, 0xe8, 0xe3, 0x93, 0xac, 0x93, 0x35, 0xe0, 0x6f, 0xd1, 0x0e, 0xba, 0xb7, 0x84,
	0xf7, 0x90, 0x91, 0x31, 0xda, 0x70, 0x56, 0xb0, 0xf5, 0x62, 0xb3, 0x2c, 0xc7, 0xc8, 0xf2, 0xc9,
	0xcb, 0x55, 0xa4, 0x28, 0xe1, 0xd8, 0x0f, 0xe6, 0xb3, 0xe0, 0xba, 0x48, 0xae, 0x10, 0x16, 0x98,
	0x7c, 0x80, 0xe5, 0x33, 0x39, 0x2f, 0xd8, 0x9f, 0x99, 0xb8, 0x82, 0xdc, 0xa3, 0xba, 0x6d, 0x2c,
	0x67, 0xc5, 0x7c, 0x7d, 0x56, 0x9d, 0xfa, 0xf7, 0xae, 0xb1, 0xb2, 0x86, 0xcb, 0xe4, 0x3e, 0xac,
	0xcc, 0x1d, 0x64, 0xe1, 0x0a, 0x7c, 0x56, 0xcc, 0x27, 0xda, 0x44, 0xb8, 0xf9, 0x62, 0x90, 0x85,
	0x78, 0xdc, 0x01, 0xa4, 0xcd, 0xf1, 0x26, 0xd9, 0xff, 0x1d, 0x49, 0xdc, 0x4e, 0xc3, 0xd8, 0x4f,
	0x1e, 0xe1, 0x16, 0xf2, 0xb1, 0x35, 0xae, 0x92, 0xf7, 0xcf, 0xde, 0x42, 0x4c, 0xa1, 0x31, 0xe4,
	0xf5, 0x24, 0xfc, 0xd2, 0xe3, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0x1e, 0x36, 0xc9, 0xcc,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PagesClient is the client API for Pages service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PagesClient interface {
	CreatePage(ctx context.Context, in *CreatePageRequest, opts ...grpc.CallOption) (*CreatePageResponse, error)
	GetPages(ctx context.Context, in *GetPagesRequest, opts ...grpc.CallOption) (*GetPagesResponse, error)
}

type pagesClient struct {
	cc *grpc.ClientConn
}

func NewPagesClient(cc *grpc.ClientConn) PagesClient {
	return &pagesClient{cc}
}

func (c *pagesClient) CreatePage(ctx context.Context, in *CreatePageRequest, opts ...grpc.CallOption) (*CreatePageResponse, error) {
	out := new(CreatePageResponse)
	err := c.cc.Invoke(ctx, "/monolith.Pages/CreatePage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pagesClient) GetPages(ctx context.Context, in *GetPagesRequest, opts ...grpc.CallOption) (*GetPagesResponse, error) {
	out := new(GetPagesResponse)
	err := c.cc.Invoke(ctx, "/monolith.Pages/GetPages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PagesServer is the server API for Pages service.
type PagesServer interface {
	CreatePage(context.Context, *CreatePageRequest) (*CreatePageResponse, error)
	GetPages(context.Context, *GetPagesRequest) (*GetPagesResponse, error)
}

func RegisterPagesServer(s *grpc.Server, srv PagesServer) {
	s.RegisterService(&_Pages_serviceDesc, srv)
}

func _Pages_CreatePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagesServer).CreatePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monolith.Pages/CreatePage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagesServer).CreatePage(ctx, req.(*CreatePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pages_GetPages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagesServer).GetPages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monolith.Pages/GetPages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagesServer).GetPages(ctx, req.(*GetPagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pages_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monolith.Pages",
	HandlerType: (*PagesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePage",
			Handler:    _Pages_CreatePage_Handler,
		},
		{
			MethodName: "GetPages",
			Handler:    _Pages_GetPages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pages.proto",
}
