// Code generated by protoc-gen-go. DO NOT EDIT.
// source: variables.proto

package monolith

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetVariablesRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVariablesRequest) Reset()         { *m = GetVariablesRequest{} }
func (m *GetVariablesRequest) String() string { return proto.CompactTextString(m) }
func (*GetVariablesRequest) ProtoMessage()    {}
func (*GetVariablesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b8b958d8129f2ed, []int{0}
}

func (m *GetVariablesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVariablesRequest.Unmarshal(m, b)
}
func (m *GetVariablesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVariablesRequest.Marshal(b, m, deterministic)
}
func (m *GetVariablesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVariablesRequest.Merge(m, src)
}
func (m *GetVariablesRequest) XXX_Size() int {
	return xxx_messageInfo_GetVariablesRequest.Size(m)
}
func (m *GetVariablesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVariablesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVariablesRequest proto.InternalMessageInfo

func (m *GetVariablesRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetVariablesResponse struct {
	Values               []*Variable `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetVariablesResponse) Reset()         { *m = GetVariablesResponse{} }
func (m *GetVariablesResponse) String() string { return proto.CompactTextString(m) }
func (*GetVariablesResponse) ProtoMessage()    {}
func (*GetVariablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b8b958d8129f2ed, []int{1}
}

func (m *GetVariablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVariablesResponse.Unmarshal(m, b)
}
func (m *GetVariablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVariablesResponse.Marshal(b, m, deterministic)
}
func (m *GetVariablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVariablesResponse.Merge(m, src)
}
func (m *GetVariablesResponse) XXX_Size() int {
	return xxx_messageInfo_GetVariablesResponse.Size(m)
}
func (m *GetVariablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVariablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVariablesResponse proto.InternalMessageInfo

func (m *GetVariablesResponse) GetValues() []*Variable {
	if m != nil {
		return m.Values
	}
	return nil
}

type FindVariablesRequest struct {
	PageId string `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	// If `names` is empty, all page variables will be returned.
	Names                []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindVariablesRequest) Reset()         { *m = FindVariablesRequest{} }
func (m *FindVariablesRequest) String() string { return proto.CompactTextString(m) }
func (*FindVariablesRequest) ProtoMessage()    {}
func (*FindVariablesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b8b958d8129f2ed, []int{2}
}

func (m *FindVariablesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindVariablesRequest.Unmarshal(m, b)
}
func (m *FindVariablesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindVariablesRequest.Marshal(b, m, deterministic)
}
func (m *FindVariablesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindVariablesRequest.Merge(m, src)
}
func (m *FindVariablesRequest) XXX_Size() int {
	return xxx_messageInfo_FindVariablesRequest.Size(m)
}
func (m *FindVariablesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindVariablesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindVariablesRequest proto.InternalMessageInfo

func (m *FindVariablesRequest) GetPageId() string {
	if m != nil {
		return m.PageId
	}
	return ""
}

func (m *FindVariablesRequest) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type FindVariablesResponse struct {
	Values               []*Variable `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FindVariablesResponse) Reset()         { *m = FindVariablesResponse{} }
func (m *FindVariablesResponse) String() string { return proto.CompactTextString(m) }
func (*FindVariablesResponse) ProtoMessage()    {}
func (*FindVariablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b8b958d8129f2ed, []int{3}
}

func (m *FindVariablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindVariablesResponse.Unmarshal(m, b)
}
func (m *FindVariablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindVariablesResponse.Marshal(b, m, deterministic)
}
func (m *FindVariablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindVariablesResponse.Merge(m, src)
}
func (m *FindVariablesResponse) XXX_Size() int {
	return xxx_messageInfo_FindVariablesResponse.Size(m)
}
func (m *FindVariablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindVariablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindVariablesResponse proto.InternalMessageInfo

func (m *FindVariablesResponse) GetValues() []*Variable {
	if m != nil {
		return m.Values
	}
	return nil
}

type CreateVariableRequest struct {
	PageId string `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	// If included, renames the variable.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// If included, updates the variable value.
	Formula              string   `protobuf:"bytes,4,opt,name=formula,proto3" json:"formula,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVariableRequest) Reset()         { *m = CreateVariableRequest{} }
func (m *CreateVariableRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVariableRequest) ProtoMessage()    {}
func (*CreateVariableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b8b958d8129f2ed, []int{4}
}

func (m *CreateVariableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVariableRequest.Unmarshal(m, b)
}
func (m *CreateVariableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVariableRequest.Marshal(b, m, deterministic)
}
func (m *CreateVariableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVariableRequest.Merge(m, src)
}
func (m *CreateVariableRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVariableRequest.Size(m)
}
func (m *CreateVariableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVariableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVariableRequest proto.InternalMessageInfo

func (m *CreateVariableRequest) GetPageId() string {
	if m != nil {
		return m.PageId
	}
	return ""
}

func (m *CreateVariableRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateVariableRequest) GetFormula() string {
	if m != nil {
		return m.Formula
	}
	return ""
}

type CreateVariableResponse struct {
	Error                *Error    `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Variable             *Variable `protobuf:"bytes,2,opt,name=variable,proto3" json:"variable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateVariableResponse) Reset()         { *m = CreateVariableResponse{} }
func (m *CreateVariableResponse) String() string { return proto.CompactTextString(m) }
func (*CreateVariableResponse) ProtoMessage()    {}
func (*CreateVariableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b8b958d8129f2ed, []int{5}
}

func (m *CreateVariableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVariableResponse.Unmarshal(m, b)
}
func (m *CreateVariableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVariableResponse.Marshal(b, m, deterministic)
}
func (m *CreateVariableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVariableResponse.Merge(m, src)
}
func (m *CreateVariableResponse) XXX_Size() int {
	return xxx_messageInfo_CreateVariableResponse.Size(m)
}
func (m *CreateVariableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVariableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVariableResponse proto.InternalMessageInfo

func (m *CreateVariableResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *CreateVariableResponse) GetVariable() *Variable {
	if m != nil {
		return m.Variable
	}
	return nil
}

type UpdateVariableRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// If included, renames the variable.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// If included, updates the variable value.
	Formula              string   `protobuf:"bytes,3,opt,name=formula,proto3" json:"formula,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateVariableRequest) Reset()         { *m = UpdateVariableRequest{} }
func (m *UpdateVariableRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateVariableRequest) ProtoMessage()    {}
func (*UpdateVariableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b8b958d8129f2ed, []int{6}
}

func (m *UpdateVariableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateVariableRequest.Unmarshal(m, b)
}
func (m *UpdateVariableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateVariableRequest.Marshal(b, m, deterministic)
}
func (m *UpdateVariableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateVariableRequest.Merge(m, src)
}
func (m *UpdateVariableRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateVariableRequest.Size(m)
}
func (m *UpdateVariableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateVariableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateVariableRequest proto.InternalMessageInfo

func (m *UpdateVariableRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateVariableRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateVariableRequest) GetFormula() string {
	if m != nil {
		return m.Formula
	}
	return ""
}

type UpdateVariableResponse struct {
	Error                *Error    `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Variable             *Variable `protobuf:"bytes,2,opt,name=variable,proto3" json:"variable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateVariableResponse) Reset()         { *m = UpdateVariableResponse{} }
func (m *UpdateVariableResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateVariableResponse) ProtoMessage()    {}
func (*UpdateVariableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b8b958d8129f2ed, []int{7}
}

func (m *UpdateVariableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateVariableResponse.Unmarshal(m, b)
}
func (m *UpdateVariableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateVariableResponse.Marshal(b, m, deterministic)
}
func (m *UpdateVariableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateVariableResponse.Merge(m, src)
}
func (m *UpdateVariableResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateVariableResponse.Size(m)
}
func (m *UpdateVariableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateVariableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateVariableResponse proto.InternalMessageInfo

func (m *UpdateVariableResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *UpdateVariableResponse) GetVariable() *Variable {
	if m != nil {
		return m.Variable
	}
	return nil
}

func init() {
	proto.RegisterType((*GetVariablesRequest)(nil), "monolith.GetVariablesRequest")
	proto.RegisterType((*GetVariablesResponse)(nil), "monolith.GetVariablesResponse")
	proto.RegisterType((*FindVariablesRequest)(nil), "monolith.FindVariablesRequest")
	proto.RegisterType((*FindVariablesResponse)(nil), "monolith.FindVariablesResponse")
	proto.RegisterType((*CreateVariableRequest)(nil), "monolith.CreateVariableRequest")
	proto.RegisterType((*CreateVariableResponse)(nil), "monolith.CreateVariableResponse")
	proto.RegisterType((*UpdateVariableRequest)(nil), "monolith.UpdateVariableRequest")
	proto.RegisterType((*UpdateVariableResponse)(nil), "monolith.UpdateVariableResponse")
}

func init() { proto.RegisterFile("variables.proto", fileDescriptor_3b8b958d8129f2ed) }

var fileDescriptor_3b8b958d8129f2ed = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xdd, 0x4a, 0xf3, 0x40,
	0x10, 0x6d, 0x93, 0xfe, 0x4e, 0xfb, 0xb5, 0x1f, 0x63, 0xab, 0x21, 0xa0, 0x96, 0x05, 0xb1, 0x78,
	0x91, 0x8b, 0xfa, 0x06, 0x96, 0x2a, 0x5e, 0x09, 0x81, 0x7a, 0xa9, 0x6c, 0xc9, 0xaa, 0x0b, 0x49,
	0x36, 0x6e, 0xd2, 0x3e, 0xae, 0xcf, 0x22, 0xd9, 0x34, 0x69, 0xd2, 0x6e, 0x11, 0x04, 0xef, 0x76,
	0x66, 0xce, 0x9c, 0x39, 0x27, 0x33, 0x81, 0xe1, 0x86, 0x4a, 0x4e, 0x57, 0x3e, 0x8b, 0x9d, 0x48,
	0x8a, 0x44, 0x60, 0x27, 0x10, 0xa1, 0xf0, 0x79, 0xf2, 0x61, 0xf7, 0x3d, 0x11, 0x50, 0x1e, 0x66,
	0x79, 0x72, 0x0d, 0x27, 0x0f, 0x2c, 0x79, 0xce, 0xd1, 0x2e, 0xfb, 0x5c, 0xb3, 0x38, 0xc1, 0xff,
	0x60, 0x72, 0x2f, 0xb6, 0xea, 0x13, 0x73, 0xda, 0x75, 0xd3, 0x27, 0xb9, 0x83, 0x51, 0x15, 0x18,
	0x47, 0x22, 0x8c, 0x19, 0xde, 0x40, 0x6b, 0x43, 0xfd, 0x35, 0xcb, 0xc0, 0xbd, 0x19, 0x3a, 0xf9,
	0x24, 0x27, 0x07, 0xbb, 0x5b, 0x04, 0x59, 0xc0, 0xe8, 0x9e, 0x87, 0xde, 0xc1, 0xb4, 0x33, 0x68,
	0x47, 0xf4, 0x9d, 0xbd, 0x72, 0xcf, 0xaa, 0x4f, 0xea, 0xd3, 0xae, 0xdb, 0x4a, 0xc3, 0x47, 0x0f,
	0x47, 0xd0, 0x0c, 0x69, 0xc0, 0x62, 0xcb, 0x50, 0x42, 0xb2, 0x80, 0xcc, 0x61, 0xbc, 0x47, 0xf3,
	0x0b, 0x2d, 0x2f, 0x30, 0x9e, 0x4b, 0x46, 0x13, 0x56, 0x54, 0x7e, 0x12, 0x83, 0xd0, 0x48, 0xe7,
	0x5b, 0xa6, 0xca, 0xaa, 0x37, 0x5a, 0xd0, 0x7e, 0x13, 0x32, 0x58, 0xfb, 0xd4, 0x6a, 0xa8, 0x74,
	0x1e, 0x12, 0x01, 0xa7, 0xfb, 0xfc, 0x5b, 0x95, 0x57, 0xd0, 0x64, 0x52, 0x0a, 0xa9, 0xe8, 0x7b,
	0xb3, 0xe1, 0x4e, 0xe4, 0x22, 0x4d, 0xbb, 0x59, 0x15, 0x1d, 0xe8, 0xe4, 0x4b, 0xb4, 0x0c, 0x85,
	0xd4, 0xd9, 0x29, 0x30, 0x64, 0x09, 0xe3, 0x65, 0xe4, 0x69, 0x0c, 0x0d, 0xc0, 0x28, 0xbc, 0x18,
	0x7c, 0xe7, 0xc3, 0xd0, 0xfb, 0x30, 0x0f, 0x7c, 0xec, 0xd3, 0xfe, 0xa9, 0x8f, 0xd9, 0x97, 0x01,
	0xdd, 0x62, 0xb5, 0xf8, 0x04, 0xfd, 0xf2, 0xd9, 0xe1, 0xf9, 0xae, 0x57, 0x73, 0xb7, 0xf6, 0xc5,
	0xb1, 0x72, 0xa6, 0x99, 0xd4, 0xd0, 0x85, 0x7f, 0x95, 0xe3, 0xc1, 0x52, 0x8b, 0xee, 0x38, 0xed,
	0xcb, 0xa3, 0xf5, 0x82, 0x73, 0x09, 0x83, 0xea, 0xae, 0xb1, 0xd4, 0xa4, 0xbd, 0x32, 0x7b, 0x72,
	0x1c, 0x50, 0xa6, 0xad, 0x7e, 0xfa, 0x32, 0xad, 0x76, 0xd7, 0x65, 0x5a, 0xfd, 0xd6, 0x48, 0x6d,
	0xd5, 0x52, 0x7f, 0xfe, 0xed, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x63, 0x14, 0x9c, 0xfb, 0x24,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VariablesClient is the client API for Variables service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VariablesClient interface {
	GetVariables(ctx context.Context, in *GetVariablesRequest, opts ...grpc.CallOption) (*GetVariablesResponse, error)
	FindVariables(ctx context.Context, in *FindVariablesRequest, opts ...grpc.CallOption) (*FindVariablesResponse, error)
	CreateVariable(ctx context.Context, in *CreateVariableRequest, opts ...grpc.CallOption) (*CreateVariableResponse, error)
	UpdateVariable(ctx context.Context, in *UpdateVariableRequest, opts ...grpc.CallOption) (*UpdateVariableResponse, error)
}

type variablesClient struct {
	cc *grpc.ClientConn
}

func NewVariablesClient(cc *grpc.ClientConn) VariablesClient {
	return &variablesClient{cc}
}

func (c *variablesClient) GetVariables(ctx context.Context, in *GetVariablesRequest, opts ...grpc.CallOption) (*GetVariablesResponse, error) {
	out := new(GetVariablesResponse)
	err := c.cc.Invoke(ctx, "/monolith.Variables/GetVariables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variablesClient) FindVariables(ctx context.Context, in *FindVariablesRequest, opts ...grpc.CallOption) (*FindVariablesResponse, error) {
	out := new(FindVariablesResponse)
	err := c.cc.Invoke(ctx, "/monolith.Variables/FindVariables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variablesClient) CreateVariable(ctx context.Context, in *CreateVariableRequest, opts ...grpc.CallOption) (*CreateVariableResponse, error) {
	out := new(CreateVariableResponse)
	err := c.cc.Invoke(ctx, "/monolith.Variables/CreateVariable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variablesClient) UpdateVariable(ctx context.Context, in *UpdateVariableRequest, opts ...grpc.CallOption) (*UpdateVariableResponse, error) {
	out := new(UpdateVariableResponse)
	err := c.cc.Invoke(ctx, "/monolith.Variables/UpdateVariable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VariablesServer is the server API for Variables service.
type VariablesServer interface {
	GetVariables(context.Context, *GetVariablesRequest) (*GetVariablesResponse, error)
	FindVariables(context.Context, *FindVariablesRequest) (*FindVariablesResponse, error)
	CreateVariable(context.Context, *CreateVariableRequest) (*CreateVariableResponse, error)
	UpdateVariable(context.Context, *UpdateVariableRequest) (*UpdateVariableResponse, error)
}

func RegisterVariablesServer(s *grpc.Server, srv VariablesServer) {
	s.RegisterService(&_Variables_serviceDesc, srv)
}

func _Variables_GetVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariablesServer).GetVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monolith.Variables/GetVariables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariablesServer).GetVariables(ctx, req.(*GetVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Variables_FindVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariablesServer).FindVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monolith.Variables/FindVariables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariablesServer).FindVariables(ctx, req.(*FindVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Variables_CreateVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariablesServer).CreateVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monolith.Variables/CreateVariable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariablesServer).CreateVariable(ctx, req.(*CreateVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Variables_UpdateVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariablesServer).UpdateVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monolith.Variables/UpdateVariable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariablesServer).UpdateVariable(ctx, req.(*UpdateVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Variables_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monolith.Variables",
	HandlerType: (*VariablesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVariables",
			Handler:    _Variables_GetVariables_Handler,
		},
		{
			MethodName: "FindVariables",
			Handler:    _Variables_FindVariables_Handler,
		},
		{
			MethodName: "CreateVariable",
			Handler:    _Variables_CreateVariable_Handler,
		},
		{
			MethodName: "UpdateVariable",
			Handler:    _Variables_UpdateVariable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "variables.proto",
}
