// Code generated by protoc-gen-go. DO NOT EDIT.
// source: variables.proto

package monolith

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetVariablesRequest struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVariablesRequest) Reset()         { *m = GetVariablesRequest{} }
func (m *GetVariablesRequest) String() string { return proto.CompactTextString(m) }
func (*GetVariablesRequest) ProtoMessage()    {}
func (*GetVariablesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b8b958d8129f2ed, []int{0}
}

func (m *GetVariablesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVariablesRequest.Unmarshal(m, b)
}
func (m *GetVariablesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVariablesRequest.Marshal(b, m, deterministic)
}
func (m *GetVariablesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVariablesRequest.Merge(m, src)
}
func (m *GetVariablesRequest) XXX_Size() int {
	return xxx_messageInfo_GetVariablesRequest.Size(m)
}
func (m *GetVariablesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVariablesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVariablesRequest proto.InternalMessageInfo

func (m *GetVariablesRequest) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type GetVariablesResponse struct {
	Values               []*Variable `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetVariablesResponse) Reset()         { *m = GetVariablesResponse{} }
func (m *GetVariablesResponse) String() string { return proto.CompactTextString(m) }
func (*GetVariablesResponse) ProtoMessage()    {}
func (*GetVariablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b8b958d8129f2ed, []int{1}
}

func (m *GetVariablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVariablesResponse.Unmarshal(m, b)
}
func (m *GetVariablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVariablesResponse.Marshal(b, m, deterministic)
}
func (m *GetVariablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVariablesResponse.Merge(m, src)
}
func (m *GetVariablesResponse) XXX_Size() int {
	return xxx_messageInfo_GetVariablesResponse.Size(m)
}
func (m *GetVariablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVariablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVariablesResponse proto.InternalMessageInfo

func (m *GetVariablesResponse) GetValues() []*Variable {
	if m != nil {
		return m.Values
	}
	return nil
}

type SetVariableRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Formula              string   `protobuf:"bytes,2,opt,name=formula,proto3" json:"formula,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetVariableRequest) Reset()         { *m = SetVariableRequest{} }
func (m *SetVariableRequest) String() string { return proto.CompactTextString(m) }
func (*SetVariableRequest) ProtoMessage()    {}
func (*SetVariableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b8b958d8129f2ed, []int{2}
}

func (m *SetVariableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetVariableRequest.Unmarshal(m, b)
}
func (m *SetVariableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetVariableRequest.Marshal(b, m, deterministic)
}
func (m *SetVariableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetVariableRequest.Merge(m, src)
}
func (m *SetVariableRequest) XXX_Size() int {
	return xxx_messageInfo_SetVariableRequest.Size(m)
}
func (m *SetVariableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetVariableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetVariableRequest proto.InternalMessageInfo

func (m *SetVariableRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetVariableRequest) GetFormula() string {
	if m != nil {
		return m.Formula
	}
	return ""
}

type SetVariableResponse struct {
	Error                *Error    `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Variable             *Variable `protobuf:"bytes,2,opt,name=variable,proto3" json:"variable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SetVariableResponse) Reset()         { *m = SetVariableResponse{} }
func (m *SetVariableResponse) String() string { return proto.CompactTextString(m) }
func (*SetVariableResponse) ProtoMessage()    {}
func (*SetVariableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b8b958d8129f2ed, []int{3}
}

func (m *SetVariableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetVariableResponse.Unmarshal(m, b)
}
func (m *SetVariableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetVariableResponse.Marshal(b, m, deterministic)
}
func (m *SetVariableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetVariableResponse.Merge(m, src)
}
func (m *SetVariableResponse) XXX_Size() int {
	return xxx_messageInfo_SetVariableResponse.Size(m)
}
func (m *SetVariableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetVariableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetVariableResponse proto.InternalMessageInfo

func (m *SetVariableResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *SetVariableResponse) GetVariable() *Variable {
	if m != nil {
		return m.Variable
	}
	return nil
}

func init() {
	proto.RegisterType((*GetVariablesRequest)(nil), "monolith.GetVariablesRequest")
	proto.RegisterType((*GetVariablesResponse)(nil), "monolith.GetVariablesResponse")
	proto.RegisterType((*SetVariableRequest)(nil), "monolith.SetVariableRequest")
	proto.RegisterType((*SetVariableResponse)(nil), "monolith.SetVariableResponse")
}

func init() { proto.RegisterFile("variables.proto", fileDescriptor_3b8b958d8129f2ed) }

var fileDescriptor_3b8b958d8129f2ed = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x35, 0x56, 0x6b, 0x33, 0x29, 0x54, 0xa6, 0x1e, 0x42, 0xb0, 0x52, 0x16, 0x84, 0xea, 0x21,
	0x87, 0xf8, 0x03, 0x22, 0x88, 0x17, 0x41, 0x58, 0xc1, 0xfb, 0x16, 0x47, 0x0c, 0xdd, 0x64, 0xea,
	0x6e, 0x52, 0xe8, 0x2f, 0xf9, 0x95, 0xd2, 0x4d, 0xb7, 0x69, 0xb1, 0xb9, 0xcd, 0xce, 0x7b, 0xf3,
	0xe6, 0xcd, 0x5b, 0x18, 0xad, 0x94, 0xc9, 0xd5, 0x5c, 0x93, 0x4d, 0x97, 0x86, 0x2b, 0xc6, 0x41,
	0xc1, 0x25, 0xeb, 0xbc, 0xfa, 0x4e, 0x86, 0x9f, 0x5c, 0xa8, 0xbc, 0x6c, 0xfa, 0xe2, 0x0e, 0xc6,
	0x2f, 0x54, 0x7d, 0x78, 0xb6, 0xa4, 0x9f, 0x9a, 0x6c, 0x85, 0x08, 0x67, 0x0b, 0x5a, 0xdb, 0x38,
	0x98, 0xf6, 0x66, 0xa1, 0x74, 0xb5, 0x78, 0x82, 0xab, 0x43, 0xaa, 0x5d, 0x72, 0x69, 0x09, 0xef,
	0xa1, 0xbf, 0x52, 0xba, 0xa6, 0x86, 0x1d, 0x65, 0x98, 0xfa, 0x5d, 0xa9, 0x27, 0xcb, 0x2d, 0x43,
	0x3c, 0x02, 0xbe, 0xb7, 0x1a, 0x7e, 0xdb, 0x25, 0xf4, 0x16, 0xb4, 0x8e, 0x83, 0x69, 0x30, 0x0b,
	0xe5, 0xa6, 0xc4, 0x18, 0x2e, 0xbe, 0xd8, 0x14, 0xb5, 0x56, 0xf1, 0xa9, 0xeb, 0xfa, 0xa7, 0xd0,
	0x30, 0x3e, 0x50, 0xd8, 0x9a, 0xb8, 0x85, 0x73, 0x32, 0x86, 0x8d, 0x13, 0x89, 0xb2, 0x51, 0xeb,
	0xe1, 0x79, 0xd3, 0x96, 0x0d, 0x8a, 0x29, 0x0c, 0x7c, 0x32, 0x4e, 0xf8, 0xb8, 0xdb, 0x1d, 0x27,
	0xfb, 0x0d, 0x20, 0xdc, 0x5d, 0x8c, 0x6f, 0x30, 0xdc, 0x4f, 0x00, 0x27, 0xed, 0xec, 0x91, 0x10,
	0x93, 0x9b, 0x2e, 0xb8, 0xf1, 0x2c, 0x4e, 0xf0, 0x15, 0xa2, 0xbd, 0x63, 0xf0, 0xba, 0x1d, 0xf8,
	0x9f, 0x52, 0x32, 0xe9, 0x40, 0xbd, 0xda, 0xbc, 0xef, 0xbe, 0xf4, 0xe1, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0x5d, 0x47, 0x9f, 0xbd, 0xfd, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VariablesClient is the client API for Variables service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VariablesClient interface {
	GetVariables(ctx context.Context, in *GetVariablesRequest, opts ...grpc.CallOption) (*GetVariablesResponse, error)
	SetVariable(ctx context.Context, in *SetVariableRequest, opts ...grpc.CallOption) (*SetVariableResponse, error)
}

type variablesClient struct {
	cc *grpc.ClientConn
}

func NewVariablesClient(cc *grpc.ClientConn) VariablesClient {
	return &variablesClient{cc}
}

func (c *variablesClient) GetVariables(ctx context.Context, in *GetVariablesRequest, opts ...grpc.CallOption) (*GetVariablesResponse, error) {
	out := new(GetVariablesResponse)
	err := c.cc.Invoke(ctx, "/monolith.Variables/GetVariables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variablesClient) SetVariable(ctx context.Context, in *SetVariableRequest, opts ...grpc.CallOption) (*SetVariableResponse, error) {
	out := new(SetVariableResponse)
	err := c.cc.Invoke(ctx, "/monolith.Variables/SetVariable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VariablesServer is the server API for Variables service.
type VariablesServer interface {
	GetVariables(context.Context, *GetVariablesRequest) (*GetVariablesResponse, error)
	SetVariable(context.Context, *SetVariableRequest) (*SetVariableResponse, error)
}

func RegisterVariablesServer(s *grpc.Server, srv VariablesServer) {
	s.RegisterService(&_Variables_serviceDesc, srv)
}

func _Variables_GetVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariablesServer).GetVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monolith.Variables/GetVariables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariablesServer).GetVariables(ctx, req.(*GetVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Variables_SetVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariablesServer).SetVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monolith.Variables/SetVariable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariablesServer).SetVariable(ctx, req.(*SetVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Variables_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monolith.Variables",
	HandlerType: (*VariablesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVariables",
			Handler:    _Variables_GetVariables_Handler,
		},
		{
			MethodName: "SetVariable",
			Handler:    _Variables_SetVariable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "variables.proto",
}
