// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resolver.proto

package resolver

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ObjectType int32

const (
	ObjectType_STRING ObjectType = 0
	ObjectType_NUMBER ObjectType = 1
	ObjectType_LIST   ObjectType = 2
	ObjectType_RECORD ObjectType = 3
	ObjectType_TUPLE  ObjectType = 4
)

var ObjectType_name = map[int32]string{
	0: "STRING",
	1: "NUMBER",
	2: "LIST",
	3: "RECORD",
	4: "TUPLE",
}

var ObjectType_value = map[string]int32{
	"STRING": 0,
	"NUMBER": 1,
	"LIST":   2,
	"RECORD": 3,
	"TUPLE":  4,
}

func (x ObjectType) String() string {
	return proto.EnumName(ObjectType_name, int32(x))
}

func (ObjectType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f5838971722c666f, []int{0}
}

type ResolveRequest struct {
	Formula              string   `protobuf:"bytes,1,opt,name=formula,proto3" json:"formula,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolveRequest) Reset()         { *m = ResolveRequest{} }
func (m *ResolveRequest) String() string { return proto.CompactTextString(m) }
func (*ResolveRequest) ProtoMessage()    {}
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5838971722c666f, []int{0}
}

func (m *ResolveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveRequest.Unmarshal(m, b)
}
func (m *ResolveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveRequest.Marshal(b, m, deterministic)
}
func (m *ResolveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveRequest.Merge(m, src)
}
func (m *ResolveRequest) XXX_Size() int {
	return xxx_messageInfo_ResolveRequest.Size(m)
}
func (m *ResolveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveRequest proto.InternalMessageInfo

func (m *ResolveRequest) GetFormula() string {
	if m != nil {
		return m.Formula
	}
	return ""
}

type ResolveResponse struct {
	Result               *Object  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolveResponse) Reset()         { *m = ResolveResponse{} }
func (m *ResolveResponse) String() string { return proto.CompactTextString(m) }
func (*ResolveResponse) ProtoMessage()    {}
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5838971722c666f, []int{1}
}

func (m *ResolveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveResponse.Unmarshal(m, b)
}
func (m *ResolveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveResponse.Marshal(b, m, deterministic)
}
func (m *ResolveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveResponse.Merge(m, src)
}
func (m *ResolveResponse) XXX_Size() int {
	return xxx_messageInfo_ResolveResponse.Size(m)
}
func (m *ResolveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveResponse proto.InternalMessageInfo

func (m *ResolveResponse) GetResult() *Object {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ResolveResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Object struct {
	Type                 ObjectType `protobuf:"varint,1,opt,name=type,proto3,enum=resolver.ObjectType" json:"type,omitempty"`
	StringValue          string     `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	NumberValue          float64    `protobuf:"fixed64,3,opt,name=number_value,json=numberValue,proto3" json:"number_value,omitempty"`
	ListValue            *List      `protobuf:"bytes,4,opt,name=list_value,json=listValue,proto3" json:"list_value,omitempty"`
	RecordValue          *Record    `protobuf:"bytes,5,opt,name=record_value,json=recordValue,proto3" json:"record_value,omitempty"`
	TupleValue           *Tuple     `protobuf:"bytes,6,opt,name=tuple_value,json=tupleValue,proto3" json:"tuple_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5838971722c666f, []int{2}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetType() ObjectType {
	if m != nil {
		return m.Type
	}
	return ObjectType_STRING
}

func (m *Object) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Object) GetNumberValue() float64 {
	if m != nil {
		return m.NumberValue
	}
	return 0
}

func (m *Object) GetListValue() *List {
	if m != nil {
		return m.ListValue
	}
	return nil
}

func (m *Object) GetRecordValue() *Record {
	if m != nil {
		return m.RecordValue
	}
	return nil
}

func (m *Object) GetTupleValue() *Tuple {
	if m != nil {
		return m.TupleValue
	}
	return nil
}

type List struct {
	Elements             []*Object `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5838971722c666f, []int{3}
}

func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (m *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(m, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

func (m *List) GetElements() []*Object {
	if m != nil {
		return m.Elements
	}
	return nil
}

type Tuple struct {
	Elements             []*Object `protobuf:"bytes,2,rep,name=elements,proto3" json:"elements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Tuple) Reset()         { *m = Tuple{} }
func (m *Tuple) String() string { return proto.CompactTextString(m) }
func (*Tuple) ProtoMessage()    {}
func (*Tuple) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5838971722c666f, []int{4}
}

func (m *Tuple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tuple.Unmarshal(m, b)
}
func (m *Tuple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tuple.Marshal(b, m, deterministic)
}
func (m *Tuple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tuple.Merge(m, src)
}
func (m *Tuple) XXX_Size() int {
	return xxx_messageInfo_Tuple.Size(m)
}
func (m *Tuple) XXX_DiscardUnknown() {
	xxx_messageInfo_Tuple.DiscardUnknown(m)
}

var xxx_messageInfo_Tuple proto.InternalMessageInfo

func (m *Tuple) GetElements() []*Object {
	if m != nil {
		return m.Elements
	}
	return nil
}

type Record struct {
	Properties           []*RecordProperty `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5838971722c666f, []int{5}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetProperties() []*RecordProperty {
	if m != nil {
		return m.Properties
	}
	return nil
}

type RecordProperty struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                *Object  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordProperty) Reset()         { *m = RecordProperty{} }
func (m *RecordProperty) String() string { return proto.CompactTextString(m) }
func (*RecordProperty) ProtoMessage()    {}
func (*RecordProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5838971722c666f, []int{6}
}

func (m *RecordProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordProperty.Unmarshal(m, b)
}
func (m *RecordProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordProperty.Marshal(b, m, deterministic)
}
func (m *RecordProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordProperty.Merge(m, src)
}
func (m *RecordProperty) XXX_Size() int {
	return xxx_messageInfo_RecordProperty.Size(m)
}
func (m *RecordProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordProperty.DiscardUnknown(m)
}

var xxx_messageInfo_RecordProperty proto.InternalMessageInfo

func (m *RecordProperty) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RecordProperty) GetValue() *Object {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("resolver.ObjectType", ObjectType_name, ObjectType_value)
	proto.RegisterType((*ResolveRequest)(nil), "resolver.ResolveRequest")
	proto.RegisterType((*ResolveResponse)(nil), "resolver.ResolveResponse")
	proto.RegisterType((*Object)(nil), "resolver.Object")
	proto.RegisterType((*List)(nil), "resolver.List")
	proto.RegisterType((*Tuple)(nil), "resolver.Tuple")
	proto.RegisterType((*Record)(nil), "resolver.Record")
	proto.RegisterType((*RecordProperty)(nil), "resolver.RecordProperty")
}

func init() { proto.RegisterFile("resolver.proto", fileDescriptor_f5838971722c666f) }

var fileDescriptor_f5838971722c666f = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xeb, 0xc4, 0x76, 0x93, 0x71, 0x95, 0x5a, 0xa3, 0x1e, 0x0c, 0xa7, 0xe0, 0x03, 0x8a,
	0x2a, 0xa8, 0x50, 0x0a, 0x12, 0x47, 0x54, 0xb0, 0x50, 0x25, 0xd3, 0x96, 0xad, 0xcb, 0x15, 0x25,
	0x65, 0x40, 0x46, 0xb6, 0xd7, 0xec, 0xae, 0x2b, 0xe5, 0x25, 0x78, 0x66, 0xb4, 0x7f, 0x12, 0x27,
	0x51, 0x24, 0x6e, 0xb3, 0xf3, 0xfd, 0xbe, 0x99, 0x1d, 0xef, 0x18, 0x26, 0x82, 0x24, 0xaf, 0x9e,
	0x48, 0x5c, 0xb4, 0x82, 0x2b, 0x8e, 0xa3, 0xf5, 0x39, 0x3d, 0x87, 0x09, 0xb3, 0x31, 0xa3, 0x3f,
	0x1d, 0x49, 0x85, 0x09, 0x1c, 0xff, 0xe4, 0xa2, 0xee, 0xaa, 0x45, 0xe2, 0x4d, 0xbd, 0xd9, 0x98,
	0xad, 0x8f, 0xe9, 0x57, 0x38, 0xdd, 0xb0, 0xb2, 0xe5, 0x8d, 0x24, 0x9c, 0x41, 0x28, 0x48, 0x76,
	0x95, 0x32, 0x6c, 0x34, 0x8f, 0x2f, 0x36, 0x9d, 0x6e, 0x97, 0xbf, 0xe9, 0x51, 0x31, 0xa7, 0xe3,
	0x19, 0x04, 0x24, 0x04, 0x17, 0xc9, 0xc0, 0x14, 0xb5, 0x87, 0xf4, 0xef, 0x00, 0x42, 0x0b, 0xe2,
	0x0c, 0x7c, 0xb5, 0x6a, 0xc9, 0x14, 0x9a, 0xcc, 0xcf, 0xf6, 0x0b, 0x15, 0xab, 0x96, 0x98, 0x21,
	0xf0, 0x05, 0x9c, 0x48, 0x25, 0xca, 0xe6, 0xd7, 0xf7, 0xa7, 0x45, 0xd5, 0x91, 0xab, 0x18, 0xd9,
	0xdc, 0x37, 0x9d, 0xd2, 0x48, 0xd3, 0xd5, 0x4b, 0x12, 0x0e, 0x19, 0x4e, 0xbd, 0x99, 0xc7, 0x22,
	0x9b, 0xb3, 0xc8, 0x6b, 0x80, 0xaa, 0x94, 0xca, 0x01, 0xbe, 0xb9, 0xfe, 0xa4, 0xef, 0x9a, 0x97,
	0x52, 0xb1, 0xb1, 0x26, 0x2c, 0x7e, 0x09, 0x27, 0x82, 0x1e, 0xb9, 0xf8, 0xe1, 0x0c, 0xc1, 0xfe,
	0xbc, 0xcc, 0xa8, 0x2c, 0xb2, 0x94, 0x35, 0xbd, 0x81, 0x48, 0x75, 0x6d, 0x45, 0xce, 0x13, 0x1a,
	0xcf, 0x69, 0xef, 0x29, 0xb4, 0xc8, 0xc0, 0x30, 0xc6, 0x91, 0xbe, 0x05, 0x5f, 0x77, 0xc6, 0x57,
	0x30, 0xa2, 0x8a, 0x6a, 0x6a, 0x94, 0x4c, 0xbc, 0xe9, 0xf0, 0xe0, 0xa7, 0xdd, 0x10, 0xe9, 0x3b,
	0x08, 0x4c, 0xa9, 0x1d, 0xdb, 0xe0, 0xbf, 0xb6, 0x2b, 0x08, 0xed, 0xad, 0xf1, 0x3d, 0x40, 0x2b,
	0x78, 0x4b, 0x42, 0x95, 0xb4, 0x6e, 0x98, 0xec, 0xcf, 0x76, 0x67, 0x89, 0x15, 0xdb, 0x62, 0xd3,
	0x5c, 0x2f, 0xd0, 0xb6, 0x8a, 0x08, 0x7e, 0xb3, 0xa8, 0xc9, 0x6d, 0x8f, 0x89, 0xf1, 0x25, 0x04,
	0xfd, 0x5b, 0x1d, 0xba, 0x94, 0x95, 0xcf, 0x33, 0x80, 0xfe, 0xb9, 0x11, 0x20, 0xbc, 0x2f, 0xd8,
	0xf5, 0xcd, 0xe7, 0xf8, 0x48, 0xc7, 0x37, 0x0f, 0x5f, 0xae, 0x32, 0x16, 0x7b, 0x38, 0x02, 0x3f,
	0xbf, 0xbe, 0x2f, 0xe2, 0x81, 0xce, 0xb2, 0xec, 0xe3, 0x2d, 0xfb, 0x14, 0x0f, 0x71, 0x0c, 0x41,
	0xf1, 0x70, 0x97, 0x67, 0xb1, 0x3f, 0xcf, 0x61, 0xe4, 0x36, 0x55, 0xe0, 0x07, 0x38, 0x76, 0x31,
	0xee, 0x4c, 0xb4, 0xbd, 0xf4, 0xcf, 0x9f, 0x1d, 0x50, 0xec, 0x8a, 0xa7, 0x47, 0xcb, 0xd0, 0xfc,
	0x34, 0x97, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x60, 0xee, 0xda, 0x46, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ResolverClient is the client API for Resolver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResolverClient interface {
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
}

type resolverClient struct {
	cc *grpc.ClientConn
}

func NewResolverClient(cc *grpc.ClientConn) ResolverClient {
	return &resolverClient{cc}
}

func (c *resolverClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, "/resolver.Resolver/Resolve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResolverServer is the server API for Resolver service.
type ResolverServer interface {
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
}

func RegisterResolverServer(s *grpc.Server, srv ResolverServer) {
	s.RegisterService(&_Resolver_serviceDesc, srv)
}

func _Resolver_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resolver.Resolver/Resolve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Resolver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resolver.Resolver",
	HandlerType: (*ResolverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resolve",
			Handler:    _Resolver_Resolve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resolver.proto",
}
