// Code generated by protoc-gen-go. DO NOT EDIT.
// source: variables.proto

package variables

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetVariablesRequest struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVariablesRequest) Reset()         { *m = GetVariablesRequest{} }
func (m *GetVariablesRequest) String() string { return proto.CompactTextString(m) }
func (*GetVariablesRequest) ProtoMessage()    {}
func (*GetVariablesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b8b958d8129f2ed, []int{0}
}

func (m *GetVariablesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVariablesRequest.Unmarshal(m, b)
}
func (m *GetVariablesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVariablesRequest.Marshal(b, m, deterministic)
}
func (m *GetVariablesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVariablesRequest.Merge(m, src)
}
func (m *GetVariablesRequest) XXX_Size() int {
	return xxx_messageInfo_GetVariablesRequest.Size(m)
}
func (m *GetVariablesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVariablesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVariablesRequest proto.InternalMessageInfo

func (m *GetVariablesRequest) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type GetVariablesResponse struct {
	Values               []*GetVariablesResponse_VariableEntry `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *GetVariablesResponse) Reset()         { *m = GetVariablesResponse{} }
func (m *GetVariablesResponse) String() string { return proto.CompactTextString(m) }
func (*GetVariablesResponse) ProtoMessage()    {}
func (*GetVariablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b8b958d8129f2ed, []int{1}
}

func (m *GetVariablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVariablesResponse.Unmarshal(m, b)
}
func (m *GetVariablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVariablesResponse.Marshal(b, m, deterministic)
}
func (m *GetVariablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVariablesResponse.Merge(m, src)
}
func (m *GetVariablesResponse) XXX_Size() int {
	return xxx_messageInfo_GetVariablesResponse.Size(m)
}
func (m *GetVariablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVariablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVariablesResponse proto.InternalMessageInfo

func (m *GetVariablesResponse) GetValues() []*GetVariablesResponse_VariableEntry {
	if m != nil {
		return m.Values
	}
	return nil
}

type GetVariablesResponse_VariableEntry struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Formula              string   `protobuf:"bytes,2,opt,name=formula,proto3" json:"formula,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVariablesResponse_VariableEntry) Reset()         { *m = GetVariablesResponse_VariableEntry{} }
func (m *GetVariablesResponse_VariableEntry) String() string { return proto.CompactTextString(m) }
func (*GetVariablesResponse_VariableEntry) ProtoMessage()    {}
func (*GetVariablesResponse_VariableEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b8b958d8129f2ed, []int{1, 0}
}

func (m *GetVariablesResponse_VariableEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVariablesResponse_VariableEntry.Unmarshal(m, b)
}
func (m *GetVariablesResponse_VariableEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVariablesResponse_VariableEntry.Marshal(b, m, deterministic)
}
func (m *GetVariablesResponse_VariableEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVariablesResponse_VariableEntry.Merge(m, src)
}
func (m *GetVariablesResponse_VariableEntry) XXX_Size() int {
	return xxx_messageInfo_GetVariablesResponse_VariableEntry.Size(m)
}
func (m *GetVariablesResponse_VariableEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVariablesResponse_VariableEntry.DiscardUnknown(m)
}

var xxx_messageInfo_GetVariablesResponse_VariableEntry proto.InternalMessageInfo

func (m *GetVariablesResponse_VariableEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetVariablesResponse_VariableEntry) GetFormula() string {
	if m != nil {
		return m.Formula
	}
	return ""
}

func init() {
	proto.RegisterType((*GetVariablesRequest)(nil), "variables.GetVariablesRequest")
	proto.RegisterType((*GetVariablesResponse)(nil), "variables.GetVariablesResponse")
	proto.RegisterType((*GetVariablesResponse_VariableEntry)(nil), "variables.GetVariablesResponse.VariableEntry")
}

func init() { proto.RegisterFile("variables.proto", fileDescriptor_3b8b958d8129f2ed) }

var fileDescriptor_3b8b958d8129f2ed = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x4b, 0x2c, 0xca,
	0x4c, 0x4c, 0xca, 0x49, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x69, 0x72, 0x09, 0xbb, 0xa7, 0x96, 0x84, 0xc1, 0xf8, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25,
	0x42, 0x42, 0x5c, 0x2c, 0xd9, 0xa9, 0x95, 0xc5, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0x9c, 0x41, 0x60,
	0xb6, 0xd2, 0x2c, 0x46, 0x2e, 0x11, 0x54, 0xb5, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0xae,
	0x5c, 0x6c, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x10, 0xe5, 0xdc, 0x46, 0xba, 0x7a, 0x08, 0x0b, 0xb1,
	0x69, 0xd0, 0x83, 0x89, 0xb8, 0xe6, 0x95, 0x14, 0x55, 0x06, 0x41, 0x35, 0x4b, 0x59, 0x73, 0xf1,
	0xa2, 0x48, 0x08, 0x09, 0x70, 0x31, 0x67, 0xa7, 0x56, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0x81, 0x98, 0x42, 0x12, 0x5c, 0xec, 0x69, 0xf9, 0x45, 0xb9, 0xa5, 0x39, 0x89, 0x12, 0x4c, 0x60,
	0x51, 0x18, 0xd7, 0x28, 0x8e, 0x8b, 0x13, 0x6e, 0x8f, 0x50, 0x20, 0x17, 0x0f, 0xb2, 0xbd, 0x42,
	0x72, 0x38, 0x1d, 0x04, 0xf6, 0xad, 0x94, 0x3c, 0x01, 0x07, 0x2b, 0x31, 0x24, 0xb1, 0x81, 0x43,
	0xce, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x56, 0xa8, 0x6e, 0x4c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VariablesClient is the client API for Variables service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VariablesClient interface {
	GetVariables(ctx context.Context, in *GetVariablesRequest, opts ...grpc.CallOption) (*GetVariablesResponse, error)
}

type variablesClient struct {
	cc *grpc.ClientConn
}

func NewVariablesClient(cc *grpc.ClientConn) VariablesClient {
	return &variablesClient{cc}
}

func (c *variablesClient) GetVariables(ctx context.Context, in *GetVariablesRequest, opts ...grpc.CallOption) (*GetVariablesResponse, error) {
	out := new(GetVariablesResponse)
	err := c.cc.Invoke(ctx, "/variables.Variables/GetVariables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VariablesServer is the server API for Variables service.
type VariablesServer interface {
	GetVariables(context.Context, *GetVariablesRequest) (*GetVariablesResponse, error)
}

func RegisterVariablesServer(s *grpc.Server, srv VariablesServer) {
	s.RegisterService(&_Variables_serviceDesc, srv)
}

func _Variables_GetVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariablesServer).GetVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/variables.Variables/GetVariables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariablesServer).GetVariables(ctx, req.(*GetVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Variables_serviceDesc = grpc.ServiceDesc{
	ServiceName: "variables.Variables",
	HandlerType: (*VariablesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVariables",
			Handler:    _Variables_GetVariables_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "variables.proto",
}
